name: "ESLint"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '34 22 * * 0'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i && npm i -g eslint
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
