name: Release and ESLint

on: 
  push:
    branches: [ main ]
    paths: 
      - "**.js"
      - "**.json"
      - "**.yaml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i && npm i -g eslint
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm i && npm i pkg -g


      - name: Build executables
        run: pkg -t node16-win sercos-parfile.js && rm sercos-parfile.js

      - name: Set env variables
        run: echo "NOW=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sercos-parfile*"
          tag: ${{ env.NOW }}
          token: ${{ secrets.GITHUB_TOKEN }}